# .github/workflows/deploy.yml
name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Prepare deployment package
        run: |
          mkdir deploy
          cp build/libs/*.jar deploy/
          cp -r scripts/ deploy/
          cp appspec.yml deploy/

      - name: Deploy to S3
        uses: actions/aws-s3@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          bucket: learnway-bucket
          region: ap-northeast-2
          source: "deploy/"
          destination: "/deploy/"

      - name: Trigger CodeDeploy
        uses: aws-actions/aws-cli-action@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: your-aws-region
          run: |
            aws deploy create-deployment \
              --application-name leanway \
              --deployment-group-name learnway \
              --deployment-config-name CodeDeployDefault.AllAtOnce \
              --s3-location bucket=learnway-bucket,bundleType=zip,key=deploy/deploy.zip
